modLoader = "javafml"
loaderVersion = "[${neoforge_loader_version},)"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''
Auroral - A winter expansion mod centered around celestial energy and cozy vibes.
'''

[[dependencies.auroral]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.auroral]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"
